### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by zheoreh** [derbyparty/derby-login#29]
zhe@zhe-X550CL:~/projects/nodes/derby-login-example$ npm start

> derby-login-example@0.0.1 start /home/zhe/projects/nodes/derby-login-example
> node server.js

Master pid  28526

/home/zhe/projects/nodes/derby-login-example/server.js:38
      app.writeScripts(store, publicDir, {extensions: ['.coffee']}, function(e
          ^
TypeError: Object #<App> has no method 'writeScripts'
  at bundleApp (/home/zhe/projects/nodes/derby-login-example/server.js:38:11)
  at /home/zhe/projects/nodes/derby-login-example/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/home/zhe/projects/nodes/derby-login-example/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/home/zhe/projects/nodes/derby-login-example/node_modules/async/lib/async.js:124:9)
  at /home/zhe/projects/nodes/derby-login-example/server.js:30:11
  at module.exports (/home/zhe/projects/nodes/derby-login-example/server/express.js:49:3)
  at /home/zhe/projects/nodes/derby-login-example/server.js:25:3
  at Racer.Derby.run (/home/zhe/projects/nodes/derby-login-example/node_modules/derby/lib/Derby.server.js:14:5)
  at Object.<anonymous> (/home/zhe/projects/nodes/derby-login-example/server.js:9:7)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by zag2art** [comment]
Please, check you derby version. I think you have the old one.
To fix it just try `rm -rf node_modules && npm install`
